idCurrency = {
    "IDR" : "indonesia rupiah",
    "INR" : "india rupe",
    "USD" : "united state dollar",
    "EUR" : "Euro MemberContries",
    "AUD" : "australian dollar",
    "HKD" : "hongkong dollar",
    "MYR" : "malaysia ringgit",
    "QAR" : "qatar riyal",
    "RUB" : "russia ruble",
    "SGD" : "singapore dollar",
    "THB" : "thailand baht",
    "GBP" : "united kingdom pound",
    "ZWD" : "zimbabwe dollar",
    "YER" : "yemen rial",
    "VND" : "viet nam dong",
    "VEF" : "venezuela bolivar",
    "UZS" : "Uzbekistan Som",
    "UYU" : "Uruguay Peso",
    "AED" : "UAE-Dirham",
    "UAH" : "Ukraine Hryvnia",
    "TVD" : "Tuvalu Dollar",
    "TRY" : "Turkey Lira",
    "TTD" : "Trinidad dan Tobago",
    "TWD" : "Taiwan New Dollar",
    "SYP" : "Syria Pound",
    "SRD" : "Suriname Dollar",
    "CHF" : "Switzerland Franc",
    "SEK" : "Sweden Krona",
    "LKR" : "Sri Lanka Rupee",
    "ZAR" : "South Africa Rand",
    "KRW" : "South Korean Won",
    "SOS" : "Somalia Shilling",
    "SBD" : "Solomon i. Dollar",
    "SCR" : "Seychelles Rupee",
    "RSD" : "Serbia Dinar",
    "SAR" : "Saudi Arabia Riyal",
    "SHP" : "SaintHelena Pound",
    "RON" : "Romania Leu",
    "PLN" : "Poland Zloty",
    "PHP" : "Philippines Peso",
    "PEN" : "Peru Sol",
    "PYG" : "Paraguay Guarani",
    "PKR" : "Pakistan Rupee",
    "NZD" : "NewZealand Dollar",
    "NPR" : "Nepal Rupee",
    "LAK" : "Laos Kip",
    "KRW" : "KoreaSouth Won",
    "KPW" : "KoreaNorth Won",
    "JMD" : "Jamaica Dollar",
    "ILS" : "Israel Shekel",
    "IRR" : "Iran Rial",
    "EGP" : "Egypt Pound",
    "DKK" : "Denmark Krone",
    "HRK" : "Croatia Kuna",
    "CRC" : "CostaRica Colon",
    "CNY" : "China YuanRenminbi",
    "CAD" : "Canada Dollar",
    "KHR" : "Cambodia Riel",
    "BND" : "Brunei D. Dollar",
    "BRL" : "Brazil Real",
    "BGN" : "Bulgaria Lev",
    "BBD" : "Barbados Dollar",
    "ARS" : "Argentina Peso",
    "AFN" : "Afghanistan Afghani",
}
